// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: api/frontend/service.proto

package frontend

import (
	reflect "reflect"
	sync "sync"

	header "github.com/personal/jazbaatipixels/api/frontend/header"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartChatSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// unique identifier for a user
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are assignable to RequestType:
	//
	//	*StartChatSessionRequest_Image
	//	*StartChatSessionRequest_Message
	RequestType isStartChatSessionRequest_RequestType `protobuf_oneof:"request_type"`
}

func (x *StartChatSessionRequest) Reset() {
	*x = StartChatSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_frontend_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChatSessionRequest) ProtoMessage() {}

func (x *StartChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_frontend_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChatSessionRequest.ProtoReflect.Descriptor instead.
func (*StartChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_frontend_service_proto_rawDescGZIP(), []int{0}
}

func (x *StartChatSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (m *StartChatSessionRequest) GetRequestType() isStartChatSessionRequest_RequestType {
	if m != nil {
		return m.RequestType
	}
	return nil
}

func (x *StartChatSessionRequest) GetImage() []byte {
	if x, ok := x.GetRequestType().(*StartChatSessionRequest_Image); ok {
		return x.Image
	}
	return nil
}

func (x *StartChatSessionRequest) GetMessage() string {
	if x, ok := x.GetRequestType().(*StartChatSessionRequest_Message); ok {
		return x.Message
	}
	return ""
}

type isStartChatSessionRequest_RequestType interface {
	isStartChatSessionRequest_RequestType()
}

type StartChatSessionRequest_Image struct {
	Image []byte `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type StartChatSessionRequest_Message struct {
	Message string `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

func (*StartChatSessionRequest_Image) isStartChatSessionRequest_RequestType() {}

func (*StartChatSessionRequest_Message) isStartChatSessionRequest_RequestType() {}

type StartChatSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespHeader *header.ResponseHeader `protobuf:"bytes,1,opt,name=resp_header,json=respHeader,proto3" json:"resp_header,omitempty"`
	// optional: will be returned only if the bot has replied, else it will be empty
	// client should handle the empty response
	Response string `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *StartChatSessionResponse) Reset() {
	*x = StartChatSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_frontend_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartChatSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChatSessionResponse) ProtoMessage() {}

func (x *StartChatSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_frontend_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChatSessionResponse.ProtoReflect.Descriptor instead.
func (*StartChatSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_frontend_service_proto_rawDescGZIP(), []int{1}
}

func (x *StartChatSessionResponse) GetRespHeader() *header.ResponseHeader {
	if x != nil {
		return x.RespHeader
	}
	return nil
}

func (x *StartChatSessionResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_api_frontend_service_proto protoreflect.FileDescriptor

var file_api_frontend_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x66, 0x72,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x1a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x72, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x64, 0x2f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x17, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x78, 0x0a, 0x18, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x68, 0x61, 0x74, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40,
	0x0a, 0x0b, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x65, 0x0a, 0x08,
	0x46, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x12, 0x59, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x66,
	0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x68, 0x61,
	0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x2f, 0x6a, 0x61, 0x7a, 0x62, 0x61,
	0x61, 0x74, 0x69, 0x70, 0x69, 0x78, 0x65, 0x6c, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x72,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_frontend_service_proto_rawDescOnce sync.Once
	file_api_frontend_service_proto_rawDescData = file_api_frontend_service_proto_rawDesc
)

func file_api_frontend_service_proto_rawDescGZIP() []byte {
	file_api_frontend_service_proto_rawDescOnce.Do(func() {
		file_api_frontend_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_frontend_service_proto_rawDescData)
	})
	return file_api_frontend_service_proto_rawDescData
}

var file_api_frontend_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_frontend_service_proto_goTypes = []interface{}{
	(*StartChatSessionRequest)(nil),  // 0: frontend.StartChatSessionRequest
	(*StartChatSessionResponse)(nil), // 1: frontend.StartChatSessionResponse
	(*header.ResponseHeader)(nil),    // 2: frontend.header.ResponseHeader
}
var file_api_frontend_service_proto_depIdxs = []int32{
	2, // 0: frontend.StartChatSessionResponse.resp_header:type_name -> frontend.header.ResponseHeader
	0, // 1: frontend.Frontend.StartChatSession:input_type -> frontend.StartChatSessionRequest
	1, // 2: frontend.Frontend.StartChatSession:output_type -> frontend.StartChatSessionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_frontend_service_proto_init() }
func file_api_frontend_service_proto_init() {
	if File_api_frontend_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_frontend_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartChatSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_frontend_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartChatSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_frontend_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*StartChatSessionRequest_Image)(nil),
		(*StartChatSessionRequest_Message)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_frontend_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_frontend_service_proto_goTypes,
		DependencyIndexes: file_api_frontend_service_proto_depIdxs,
		MessageInfos:      file_api_frontend_service_proto_msgTypes,
	}.Build()
	File_api_frontend_service_proto = out.File
	file_api_frontend_service_proto_rawDesc = nil
	file_api_frontend_service_proto_goTypes = nil
	file_api_frontend_service_proto_depIdxs = nil
}
