// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: api/frontend/header/response.proto

package header

import (
	reflect "reflect"
	sync "sync"

	errors "github.com/personal/jazbaatipixels/api/frontend/errors"
	rpc "github.com/personal/jazbaatipixels/api/rpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResponseHeader is a field that should be a part of every response message
type ResponseHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    *rpc.Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorView *errors.ErrorView `protobuf:"bytes,2,opt,name=error_view,json=errorView,proto3" json:"error_view,omitempty"`
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_frontend_header_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_frontend_header_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_api_frontend_header_response_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseHeader) GetStatus() *rpc.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ResponseHeader) GetErrorView() *errors.ErrorView {
	if x != nil {
		return x.ErrorView
	}
	return nil
}

var File_api_frontend_header_response_proto protoreflect.FileDescriptor

var file_api_frontend_header_response_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2f, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x1a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x72, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x64, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x70, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x76, 0x69, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66,
	0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x56, 0x69, 0x65, 0x77, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x56,
	0x69, 0x65, 0x77, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x2f, 0x6a, 0x61, 0x7a, 0x62, 0x61,
	0x61, 0x74, 0x69, 0x70, 0x69, 0x78, 0x65, 0x6c, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x72,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_frontend_header_response_proto_rawDescOnce sync.Once
	file_api_frontend_header_response_proto_rawDescData = file_api_frontend_header_response_proto_rawDesc
)

func file_api_frontend_header_response_proto_rawDescGZIP() []byte {
	file_api_frontend_header_response_proto_rawDescOnce.Do(func() {
		file_api_frontend_header_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_frontend_header_response_proto_rawDescData)
	})
	return file_api_frontend_header_response_proto_rawDescData
}

var file_api_frontend_header_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_frontend_header_response_proto_goTypes = []interface{}{
	(*ResponseHeader)(nil),   // 0: frontend.header.ResponseHeader
	(*rpc.Status)(nil),       // 1: rpc.Status
	(*errors.ErrorView)(nil), // 2: frontend.errors.ErrorView
}
var file_api_frontend_header_response_proto_depIdxs = []int32{
	1, // 0: frontend.header.ResponseHeader.status:type_name -> rpc.Status
	2, // 1: frontend.header.ResponseHeader.error_view:type_name -> frontend.errors.ErrorView
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_frontend_header_response_proto_init() }
func file_api_frontend_header_response_proto_init() {
	if File_api_frontend_header_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_frontend_header_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_frontend_header_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_frontend_header_response_proto_goTypes,
		DependencyIndexes: file_api_frontend_header_response_proto_depIdxs,
		MessageInfos:      file_api_frontend_header_response_proto_msgTypes,
	}.Build()
	File_api_frontend_header_response_proto = out.File
	file_api_frontend_header_response_proto_rawDesc = nil
	file_api_frontend_header_response_proto_goTypes = nil
	file_api_frontend_header_response_proto_depIdxs = nil
}
